"""Atualizando modelo Contrato com JSON para locais e ajuste em datas/valor

Revision ID: 71cf624f0f43
Revises: 
Create Date: 2025-06-15 16:41:09.235739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cf624f0f43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locais_evento', sa.JSON(), nullable=True))
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('data_ensaio',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('horario_ensaio',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('cidade_ensaio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('data_evento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('horario_evento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.drop_column('cidade_evento')
        batch_op.drop_column('cidade_estado_evento')
        batch_op.drop_column('local_evento')
        batch_op.drop_column('estado_evento')
        batch_op.drop_column('cidade_estado_ensaio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_estado_ensaio', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado_evento', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('local_evento', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade_estado_evento', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cidade_evento', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('horario_evento',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_evento',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('cidade_ensaio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('horario_ensaio',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_ensaio',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('locais_evento')

    # ### end Alembic commands ###
